jobs:
  - job: Test
    strategy:
        matrix:
            Linux:
                vmImage: ubuntu-latest
            macOS:
                vmImage: macOS-latest
            Windows:
                vmImage: windows-latest
    pool:
        vmImage: $(vmImage)
    steps:
      - script: sudo add-apt-repository ppa:plt/racket && sudo apt-get update && sudo apt-get install --no-install-recommends -y racket racket-doc
        displayName: Install Racket (Linux)
        condition: eq(variables['Agent.OS'], 'Linux')
      - script: brew cask install racket
        displayName: Install Racket (macOS)
        condition: eq(variables['Agent.OS'], 'Darwin')
      - script: "cinst racket && echo ##vso[task.prependpath]%ProgramFiles%\\Racket"
        displayName: Install Racket (Windows)
        condition: eq(variables['Agent.OS'], 'Windows_NT')
      - script: raco pkg install --auto cover-cobertura
        displayName: Install coverage tools
      - script: raco cover -f html -f cobertura .
        displayName: Run tests with coverage
      - task: PublishCodeCoverageResults@1
        displayName: Publish coverage result
        condition: eq(variables['Agent.OS'], 'Linux')
        inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: coverage/cobertura.xml
            reportDirectory: coverage
      - task: PublishBuildArtifacts@1
        displayName: Archive HTML coverage report
        condition: eq(variables['Agent.OS'], 'Linux')
        inputs:
            pathtoPublish: coverage
            artifactName: coverage-report
